version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-buster
    steps:
      - checkout
      - run: sudo apt-get -q update && sudo apt-get -qy install shellcheck make bash
      - run: git clone https://github.com/sstephenson/bats.git && sudo ./bats/install.sh /usr/local
      - run: make
